@echo off
echo Starting Crypto Crash Game Backend...
echo.
echo 1. Installing dependencies...
call npm install
echo.
echo 2. Seeding database...
call npm run seed
echo.
echo 3. Starting server...
call npm start